site_name: PyPure
repo_url: https://github.com/pypure-dev/pypure
repo_name: GitHub
site_author: ZytroCode
site_description: A powerful game engine written python.

nav:
  - "Home": "index.md"
  - "Installation": "installation.md"

theme:
  name: material
  palette:
    scheme: default
    accent: indigo
  features:
    - toc.integrate
    - header.autohide
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
plugins:
  - "section-index"
